name: Generatic documentation using protoc-gen-doc
on:
  push:
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: docker details
        run: |
          docker --version

      - name: checkout current repository
        uses: actions/checkout@v2.4.0

      - name: log current directory details
        run: |
          pwd
          ls -a
      - name: pull protoc-gen-doc image
        run: |
          docker pull pseudomuto/protoc-gen-doc

      - name: generate gRPC doc
        run: |
          docker run --rm \
            -v $(pwd)/doc:/out \
            -v $(pwd)/proto:/protos \
            pseudomuto/protoc-gen-doc

      - name: print generated grpc doc
        run: |
          cat doc/index.html
