name: Generatic documentation using protoc-gen-doc
on:
  push:
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: docker details
        run: |
          docker --version

      - name: checkout current repository
        uses: actions/checkout@v2.4.0

      - name: log current directory details
        run: |
          pwd
          ls -a
